routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('asset_unit', 'AssetUnitController');
// Route::resource('asset_Unit/{asset_unit}', 'AssetUnitController');

app/Asset_Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Asset_Unit extends Model
{
	use SoftDeletes;
    public function asset_category(){
    	return $this->belongsTo('App\Asset_Category');
    }

    protected $fillable = ['name', 'description', 'category_id', 'images'];

}

app/Http/Controllers/AssetUnitController.php
<?php

namespace App\Http\Controllers;

use App\Asset_Unit;
use Illuminate\Http\Request;
use Str;
use App\Asset_Category;

class AssetUnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('asset_units.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'image'=> 'required|image|max:3000'
        ]);

        // echo "Hello World";

        $file = $request->file('image');


        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

        $file_extension = $file->extension();

        $random_chars = Str::random(10);

        $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_".$file_name.".".$file_extension;


        $filepath = $file->storeAs('images',$new_file_name,'public');

        $data = $request->all(
        'name',
        'category',
        'description'
        );

        extract($data);

        $assets = new Asset_Unit;
        $assets->name = $name;
        $assets->category_id = $category;
        $assets->description = $description;
        $assets->images = $filepath;
        $assets->save();


        // Asset_Unit::create([
        //     'name' => $name,
        //     'category_id' => $category,
        //     'description' => $description,
        //     'images' => $filepath
        // ]);

        // $assets = new Asset_Unit;

        return redirect(route('asset_unit.show',['asset_unit'=> $assets->id]));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Asset_Unit  $asset_Unit
     * @return \Illuminate\Http\Response
     */
    public function show(Asset_Unit $asset_unit)
    {
        // Asset_unit::all();
        dd($asset_unit);
        // return view('asset_units.show')->with('asset_unit', $asset_unit);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Asset_unit  $asset_unit
     * @return \Illuminate\Http\Response
     */
    public function edit(Asset_unit $asset_unit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Asset_unit  $asset_unit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Asset_unit $asset_unit)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Asset_unit  $asset_unit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Asset_unit $asset_unit)
    {
        //
    }
}

resources/views/asset_units/create.blade.php
@extends('layouts.app')

@section('content')

	<section class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h1>Add Item</h1>
				@if ($errors->any())
					@foreach($errors->all() as $error)
						<div class="alert alert-danger">
							<small><p class="">{{$error}}</p></small>
						</div>
					@endforeach
				@endif
				<form method="POST" enctype="multipart/form-data" action="{{route('asset_unit.store')}}">
					@csrf
					<div class="form-group">
						<label for="name">Name:</label>
						<input type="text" name="name" id="name" class="form-control">
					</div>
					<div class="form-group">
						<label for="category">Category:</label>
						<select class="form-control" id="category" name="category">
							<option value="1">Category 1</option>
						</select>
					</div>

					<div class="form-group">
						<label for="description">Description:</label>
						<textarea name="description" id="description" class="form-control"></textarea>
					</div>
					<div class="form-group">
						<label for="image">Image:</label>
						<input type="file" name="image" id="image" class="form-control-file">
					</div>
					<button class="btn btn-primary btn-block">Add Item</button>
				</form>

			</div>
		</div>
		
	</section>
@endsection

resources/views/asset_units/show.blade.php
@extends('layouts.app')

@section('content')

	<section class="container">
		<div class="row">
			
			<div class="col-12 col-md-8 mx-auto">
				{{$asset_Unit}}

				<div class="card">
					<img src="{{url('/public/'.$asset_Unit->images)}}">
					
				</div>
				
			</div>
			
		</div>
		
	</section>

@endsection